backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Main Hero Title, name: main_hero_title, widget: string}
          - {label: Main Hero Subtitle, name: main_hero_subtitle, widget: string }